module.exports={
    ensureAuth:(req,res,next)=>{
        if(req.session.isLoggedIn){
            next();
        }else{
            res.redirect("/login");
        }
    },
    ensureGuest:(req,res,next)=>{
        if(req.session.isLoggedIn){
            res.redirect("/");
        }else{
            next();
        }
    }
}